language: r
cache: packages
  
install:
  - ./travis-tool.sh install_deps
  - R -e 'install.packages("devtools")'
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
