language: r
sudo: false
cache: packages
 
r_packages:
- install_deps
- devtools
  
script: 
- ./travis-tool.sh run_tests
- R CMD build .
- R CMD check *tar.gz --as-cran

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
